name: Build and upload to PyPI

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: dockcross/manylinux2014-x64

jobs:
  build_windows_mac_wheels:
    name: Build wheel for ${{ matrix.os }} with python${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        include:
          - os: windows-latest
            sys_pkgs: choco install swig
          - os: macos-latest
            sys_pkgs: brew install swig

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      #     Had issues with not all files being pulled and this somehow resolved it
      - name: Fix submodules
        run: |
          rm -rf epanet-msx
          git submodule update

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version}}'

      - name: Setup dependencies
        run: |
          ${{matrix.sys_pkgs}}
          pip install -r build-requirements.txt

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  build_linux_wheels:
    name: Build wheels on linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      #     Had issues with not all files being pulled and this somehow resolved it
      - name: Fix submodules
        run: |
          rm -rf epanet-msx
          git submodule update

      - name: Install
        run: |
          docker pull $DOCKER_IMAGE
          docker run --rm $DOCKER_IMAGE > ./dockcross
          chmod +x ./dockcross
      - name: Script
        run: ./dockcross scripts/build-wheels.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./combined-dist/*.manylinux2014_x86_64.whl



#  build_sdist:
#    name: Build source distribution
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: true
#      #     Had issues with not all files being pulled and this somehow resolved it
#      - name: Fix submodules
#        run: |
#          rm -rf epanet-msx
#          git submodule update
#
#      - uses: actions/setup-python@v2
#        name: Install Python
#        with:
#          python-version: '3.8'
#
#      - name: Install dependencies
#        run: |
#          apt update
#          apt install swig -y
#          pip install scikit-build cmake
#      - name: Build sdist
#        run: python setup.py sdist
#
#      - uses: actions/upload-artifact@v2
#        with:
#          path: dist/*.tar.gz