name: Build and upload to PyPI

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: dockcross/manylinux2014-x64

jobs:
  build_windows_mac_wheels:
    name: Build wheel for ${{ matrix.os }} with python${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        include:
          - os: windows-latest
            sys_pkgs: choco install swig
            rm_dir: rmdir /S /Q epanet-msx
          - os: macos-latest
            sys_pkgs: brew install swig
            rm_dir: rm -rf epanet-msx

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      #     Had issues with not all files being pulled and this somehow resolved it
      - name: Fix submodules
        run: |
          ${{matrix.rm_dir}}
          git submodule update

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version}}'

      - name: Setup dependencies
        run: |
          ${{matrix.sys_pkgs}}
          pip install scikit-build==0.11.1 cmake==3.18.4

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  build_linux_wheels:
    name: Build wheels on linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      #     Had issues with not all files being pulled and this somehow resolved it
      - name: Fix submodules
        run: |
          rm -rf epanet-msx
          git submodule update

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
          build-requirements: 'cmake==3.18.4 scikit-build==0.11.1'
          system-packages: 'swig'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*-manylinux*.whl



#  build_sdist:
#    name: Build source distribution
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: true
#      #     Had issues with not all files being pulled and this somehow resolved it
#      - name: Fix submodules
#        run: |
#          rm -rf epanet-msx
#          git submodule update
#
#      - uses: actions/setup-python@v2
#        name: Install Python
#        with:
#          python-version: '3.8'
#
#      - name: Install dependencies
#        run: |
#          apt update
#          apt install swig -y
#          pip install scikit-build cmake
#      - name: Build sdist
#        run: python setup.py sdist
#
#      - uses: actions/upload-artifact@v2
#        with:
#          path: dist/*.tar.gz